cc_library(
    name = "api",
    srcs = [
        "connection.h",
        "game_session.h",
        "managed_connection.h",
        "message.h",
    ],
    visibility = ["//server:__subpackages__"],
    deps = ["//server/game/objects"],
)
