load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "mocks",
    srcs = [
        "mock_player.h",
        "mock_trick.h",
    ],
    visibility = ["//tests:__subpackages__"],
    deps = [],
)
