cc_library(
    name = "util",
    srcs = [
        "assertions.h",
        "constants.h",
        "dates.h",
        "death.h",
        "env.h",
        "logging.h",
        "types.h",
    ],
    visibility = ["//server:__subpackages__"],
    deps = [
        "@boost.asio",
        "@nlohmann_json//:json",
    ],
)
