name: GTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Externals
      run: |
        setup.sh

    - name: Set up CMake
      uses: lukka/run-cmake@v1

    - name: Build and run Google Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
