name: GTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Externals
      run: |
        bash setup.sh

    - name: Install Boost
      run: |
        sudo apt-get install -y libboost-all-dev
        boostversion=$(ls /usr/include/boost | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
        echo "Boost version: $boostversion"

    - name: Install nlohmann-json
        run: |
            sudo apt-get install -y nlohmann-json-dev

    - name: Set up CMake
      uses: lukka/run-cmake@v1

    - name: Build and run Google Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
